site_name: Hyperledger Fabric
theme: readthedocs
site_description: 'Welcome to the Hyperledger fabric documentation'
site_favicon: favicon.ico
site_dir: 'site'

pages:

- Home: index.md
- Glossary: glossary.md
- ProtocolSpec: protocol-spec.md
- Protocol Spec zh: protocol-spec_zh.md
- Usecases: biz/usecases.md

- Dev-Setup:

        - Fabric Developer Setup: dev-setup/devenv.md
        - BuildingFabric: dev-setup/build.md
        - FabricDeveloperSetup: dev-setup/devenv.md
- Setup:

        - Chaincode or Application Developer Setup: Setup/Chaincode-setup.md
        - Fabric Network Setup: Setup/Network-setup.md
        - NodeSDK Setup: Setup/NodeSDK-setup.md
        - CA Setup: Setup/ca-setup.md
        - Logging: Setup/logging-control.md
- Gerrit:

        - Gerrit Introduction: Gerrit/gerrit.md
        - LF Account: Gerrit/lf-account.md
        - Best Practices: Gerrit/best-practices.md
        - Changes: Gerrit/changes.md
        - Gerrit Review: Gerrit/reviewing.md
- API's:

        - Chaincode APIs: API/ChaincodeAPI.md
        - Core API: API/CoreAPI.md
        - CA API: API/MemberServicesAPI.md
        - System Chaincode: SystemChaincodes/noop.md
- FAQ:

        - ChainCodeFAQ: FAQ/chaincode_FAQ.md
        - ConfidentialityFAQ: FAQ/confidentiality_FAQ.md
        - ConsensusFAQ: FAQ/consensus_FAQ.md
        - Identity ManagementFAQ: FAQ/identity_management_FAQ.md
        - UsageFAQ: FAQ/usage_FAQ.md

- Tech:

       - Application ACL: tech/application-ACL.md
       - Attributes: tech/attributes.md
       - Best Practices: tech/best-practices.md

markdown_extensions:
       - smarty
       - toc:
           permalink: True
       - sane_lists

extra_css:
       - css/extra.css
       - css/second_extra.css

strict: true

copyright: Copyright &copy; 2016 IBM Corp. <br></br>Contributed to the Hyperledger Project under the <a href="https://github.com/hyperledger/fabric/blob/master/LICENSE" target="_blank">Apache Software License 2.0</a>
